[Variables]
;Find your weather code at Weather.com (like CAXX0041 below) and replace the one in this file.
WeatherCode=CAXX0041
--------------------------RSS Variables------------------------------
URL=http://newsrss.bbc.co.uk/rss/newsonline_world_edition/front_page/rss.xml
Title=News   |
Link=http://news.bbc.co.uk/
Browser=firefox.exe


update.Spd=90
Substitute="&amp;":"&","&quot;":"","&Quot;":"","&lt;br&gt;":"","![CDATA[":"","]]":"","...":"","<":"",">":"","/PRE&gt;":"","PRE&gt;":"","&lt;":""

-----------------------------------------------------------------------



App1=uTOR

App1Path=C:\Program Files\uTorrent\uTorrent.exe


App2=ILLU

App2Path=C:\Program Files\Adobe\Adobe Illustrator CS4\Support Files\Contents\Windows\Illustrator.exe


App3=WORD

App3Path=C:\Program Files\Microsoft Office\Office12\WINWORD.EXE


App4=DREAM


App4Path=C:\Program Files\Adobe\Adobe Dreamweaver CS4\Dreamweaver.exe


App5=PSHP

App5Path=C:\Program Files\Adobe\Adobe Photoshop CS4\Photoshop.exe

App6=iTUN

App6Path=itunes.exe

App7=FFOX

App7Path=firefox.exe

App8=FLZA

App8Path=C:\Program Files\FileZilla FTP Client\filezilla.exe

App9=MSN

App9Path=C:\Program Files\Windows Live\Messenger\msnmsgr.exe

Browser=firefox.exe


Color1=35, 31, 32

Font=Raleway


