[Rainmeter]

LocalFont="#SKINSPATH#INFO TIME\Variables\Fonts\ITCAvantGardePro-XLt.ttf"

[Variables]
FontFace=ITC Avant Garde Pro XLt

Color0=0,0,0,1
Color=255,255,255,255
Color1=255,255,255,200
Color2=255,255,255,160
Color3=255,255,255,75
Color4=0,0,0,20
Color5=75,75,75,255
Color6=0,0,0,160

Bar1=2,192,255
Bar2=225,225,225,35

FontSize0=70
FontSize=55
FontSize1=35
FontSize2=22
FontSize3=18
FontSize4=12
FontSize5=10

;---

MonthName="January":"Styczeñ","February":"Luty","March":"Marzec","April":"Kwiecieñ","May":"Maj","June":"Czerwiec","July":"Lipiec","August":"Sierpieñ","September":"Wrzesieñ","October":"PaŸdziernik","November":"Listopad","December":"Grudzieñ"
DayName="Sunday":"Niedziela","Monday":"Poniedzia³ek","Tuesday":"Wtorek","Wednesday":"Œroda","Thursday":"Czwartek","Friday":"Pi¹tek","Saturday":"Sobota"
DayMonthName="Sunday":"Niedziela","Monday":"Poniedzia³ek","Tuesday":"Wtorek","Wednesday":"Œroda","Thursday":"Czwartek","Friday":"Pi¹tek","Saturday":"Sobota","January":"Styczeñ","February":"Luty","March":"Marzec","April":"Kwiecieñ","May":"Maj","June":"Czerwiec","July":"Lipiec","August":"Sierpieñ","September":"Wrzesieñ","October":"PaŸdziernik","November":"Listopad","December":"Grudzieñ"
