


[Variables]


BubbleLink1=https://www.reddit.com/
BubbleLink2=chrome.exe
BubbleLink3=WINWORD.EXE
BubbleLink4=C:\Program Files (x86)\Steam\Steam.exe
BubbleLink5=https://www.youtube.com/
BubbleLink6=C:\Users\99villages\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Spotify
BubbleLink7=https://www.facebook.com/
BubbleLink8=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\TeamSpeak 3 Client
BubbleLink9=http://gmail.com/
BubbleLink10=C:\Program Files (x86)\Minecraft\MinecraftLauncher.exe



XmenLink1=http://www.gamespot.com/
XmenName1=GameSpot

XmenLink2=https://www.youtube.com/
XmenName2=YouTube

XmenLink3=https://www.ign.com
XmenName3=IGN

XmenLink4=http://deviantart.com/
XmenName4=DeviantArt


XmenLink5=https://www.facebook.com
XmenName5=FaceBook

XmenLink6=http://www.imdb.com/
XmenName6=IMDB


