
[Variables]

;User name without @gmail.com

UserName=99villages.manfort

Password=444virus

Zipcode=UKXX0085

CMXX0001

Shortcut1=C:\Windows\System32\rundll32.exe user32.dll, LockWorkStation

Shortcut2=shutdown.exe -l 

Shortcut3=shutdown.exe -h

Shortcut4=shutdown.exe -r -t 0

Shortcut5=shutdown.exe -s -t 0

InfoPic=Maria Hill






Tscale=m
TempScale=K
ScaleUnit=K
Name1=Disk C
Name2=CPU
MaxTemp1=343
MaxTemp2=378
MaxGPUTemp=378
GPUNumber=0
HDDNumber=4
CoreNumber=5
HoloName1=Age
HoloAns1=??
HoloName2=Gendre
HoloAns2=Male
Identity=%1
Height=1.62
Weight=85
HeartBeats=14

Font1=Gliscor Gothic
Font2=Myriad Pro
Font3=Ebrima
Font4=Digital
Font5=Cambria
Font6=Arial
Font7=Segoe UI
Font8=Impact

Drive1=C:
Drive2=D:
Drive3=F:
Drive4=G:


DownMax = 1048576
UpMax =1048576

Flare1=0
Flare=1

WeatherIcons=#ROOTCONFIGPATH#\@Resources\Weathericons
;------------------------Time Format----------

Format="%I"
Format2="%I:%M"




Hour=I

;---


Path1=C:\Users\99villages
Path1Name=%1

Path2=::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
Path2Name=Computer

Path3=::{450D8FBA-AD25-11D0-98A8-0800361B1103}
Path3Name=Documents


Path4=PhotoShop.exe
path4Name=Photoshop

Path5=Firefox.exe
Path5Name=Firefox



Llink1=www.twitter.com
Llink2=www.facebook.com
Llink3=www.skype.com
Llink4=www.msn.com


Link1=C:\
Link2=::{645FF040-5081-101B-9F08-00AA002F954E}
Link3=
Link4=D:\Program Files
Link5=cat


Name1=Downloads
Name2=Trash
Name3=Utorrent
Name4=PES 2017
Name5=cat

Hour=I

Nname1=ID:
Nname2=Age:
Nname3=Gendre:
Nname4=Height:
Nname5=Eye Color:
Nname6=Hair Color:


Answer1=%1
Answer2=23
Answer3=Male
Answer4=1,8m
Answer5=Brown
Answer6=Black

NeonLightName=Images/Visualisers/Neonlights/ray
NeonLightName2=Images/Visualisers/Neonlights/ray2


NeonLightPers=Images/Perspective/p
NeonLightPers2=Images/Perspective/pr

Circle=Dots

MusicPlayer=AIMP
